checking for return values during build

diff --git a/.github/workflows/joan_test_workflow.yml b/.github/workflows/joan_test_workflow.yml
--- a/.github/workflows/joan_test_workflow.yml
+++ b/.github/workflows/joan_test_workflow.yml
@@ -26,10 +26,15 @@ jobs:
           SOLUTION_NAME=aws-media-services-application-mapper
           VERSION=v1.9.0
           export PATH="$HOME/.local/bin:$PATH"
-          pip install testresources
+          #pip install testresources
           pip install --quiet --upgrade --force-reinstall -r source/msam/requirements.txt
+          if [ "$?" -ne "0" ]; then
+            echo "ERROR: Installing system packages."
+            exit 1
+          fi
           cd deployment
           ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
           # ls -lah /home/runner/work/aws-media-services-application-mapper/aws-media-services-application-mapper/deployment/*
+      - name: Run deployment script
           cd $RUNNER_WORKSPACE/$SOLUTION_NAME/deployment
           ./deploy.sh -b $DIST_OUTPUT_BUCKET -s $SOLUTION_NAME -v $VERSION -r us-west-2 -p default -a none -t dev
