install required  pkgs

diff --git a/.github/workflows/post-pipeline-workflow.yml b/.github/workflows/post-pipeline-workflow.yml
--- a/.github/workflows/post-pipeline-workflow.yml
+++ b/.github/workflows/post-pipeline-workflow.yml
@@ -101,6 +101,14 @@ jobs:
     steps:
       - name: Check Out Repo
         uses: actions/checkout@v2
+      - name: Install required system packages
+        run: |
+          pip install --upgrade --force-reinstall -r deployment/requirements.txt 2> error.txt
+          if [ -s error.txt ]; then
+            echo "ERROR: System package installation failed."
+            cat error.txt
+            exit 1
+          fi
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@master
         with:
